apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-todo
  template:
    metadata:
      labels:
        app: node-todo
    spec:
      containers:
      - name: node-todo
        image: your-dockerhub-username/node-todo:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-todo-service
spec:
  type: NodePort
  selector:
    app: node-todo
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
